### ISSUE TITLE
Create Contributors markdown file 

### ISSUE THREAD

**Issue by Vishwas-10** [Vishwas-10/DSA-SHEET#5]
[1] Create contributors file
[2] Update the readme file about How to update the contributor file

**Comment by pragyaasapkota** [comment]
Please state if you want contributors.json file.

**Comment by pragyaasapkota** [comment]
Or any other kind of file - please specify

**Comment by pragyaasapkota** [comment]
And assign me. 
I will ready them for you.

**Comment by Vishwas-10** [comment]
> Please state if you want contributors.json file.

markdown file of the format 
```
# Contributors

- []()
```

and add instructions in the readme file about how to add into contributors.md file

**Comment by Vishwas-10** [comment]
> And assign me.
> I will ready them for you.

Its an open issue who ever pushes pr first I'll merge

**Comment by Pragya2056** [comment]
Please assign this to me

**Comment by pragyaasapkota** [comment]
@Vishwas-10

**Comment by pragyaasapkota** [comment]
> > Please state if you want contributors.json file.
> 
> markdown file of the format
> 
> ```
> # Contributors
> 
> - []()
> ```
> 
> and add instructions in the readme file about how to add into contributors.md file

Okay. I will add in the format along the instruction on the readme file.

**Comment by pragyaasapkota** [comment]
- [Github username] (github profile link)

**Comment by pragyaasapkota** [comment]
> * [Github username] (github profile link)

@Vishwas-10 
Please assure me this is the format.

**Comment by Vishwas-10** [comment]
sure 👍

**Comment by pragyaasapkota** [comment]
This issue was worked on in #6

**Comment by pragyaasapkota** [comment]
@Vishwas-10 
Please look at it.
